[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "serve -s build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envs]
REACT_APP_API_URL = "https://api.collegedesk.railway.app"
PORT = "3000"
NODE_ENV = "production"
CI = "false"