[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && CI=false npm run build"

[deploy]
startCommand = "npx serve -s build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envs]
REACT_APP_API_URL = "https://api.collegedesk.railway.app"
PORT = "3000"
NODE_ENV = "production"
CI = "false"
NPM_CONFIG_PRODUCTION = "false"
NODE_OPTIONS = "--max_old_space_size=4096"
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_YARN_ENABLE = "false"